Send_Emails/Send_Emails/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path("",include("main.urls")),
	path("admin/", admin.site.urls),

	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Send_Emails/main/urls.py
from main import views
from django.urls import path
from django.contrib import admin

app_name="main"
urlpatterns = [
	path("",views.index,name="index"),
	path("signin/",views.signin,name="signin"),
	path("signout/",views.signout,name="signout"),
	path("admin/", admin.site.urls),
]

Send_Emails/main/models.py
from django.db import models
from django.contrib.auth.models import User

Send_Emails/main/forms.py
from django import forms
from django.contrib.auth.models import User
from main.models import UserProfile
 

Send_Emails/main/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
import json

def GetJson(request, backbone_dict = {}): #returns the desired dictionary or one explaining the error depending on if it was correct or not
	if request.method == "POST":
		try:
			print(request.body)
			json_dict = json.loads(request.body.decode('utf-8'))
		except:
			return {"error":"incorrectly formatted request"}
		if not json_dict.keys() == backbone_dict.keys():
			return {"error":"missing parameters in request"}
		return json_dict
	return {"error":"incorrect request method"}


def signin(request):
	if request.method == 'POST':
		login_dict = GetJson(request,backbone_dict = {"username":"","password":""})
		print(login_dict)
		if("error" in login_dict):
			login_dict["status"] = "not ok"
			return JsonResponse(login_dict)
		user = authenticate(username=login_dict["username"], password=login_dict["password"])
		if user:
			if user.is_active:
				login(request, user)
				return JsonResponse({"status":"ok"})
			else:
				return JsonResponse({"error":"disabled account","status":"not ok"})
		else:
			return JsonResponse({"error":"Incorrect login details","status":"not ok"})
		
	return render(request,"main/signin.html")

def signout(request):
	logout(request)
	return HttpResponseRedirect(reverse("main:index"))

def logged_in_or_redirect(view_function):
	def wrapper(*args,**kwargs):
		if not args[0].user.is_authenticated:
			return HttpResponseRedirect(reverse("main:signin"))
		return view_function(*args,**kwargs)
	return wrapper

@logged_in_or_redirect	
def index(request):
	return render(request,"main/index.html")

Send_Emails/templates/main/base.html
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="UTF-8" />
 		<title></title>
	</head>
	<body>
		<div>
			<a href="{% url 'main:index' %}">Home Page</a>
			<a href="{% url "main:signout" %}">Logout</a>
			{% if user.is_authenticated %}
				<a id="username_title" href="">{{ user.username }}</a>
			{% endif %}	
		</div>
		<div>
                        {% block main_block %}
                                <div><strong>"Main Block Content Here"</strong><br /></div> 
                        {% endblock%}
                </div>
	</body>
</html>

Send_Emails/templates/main/index.html
{% extends 'main/base.html' %}

{% block main_block %}
	<h1>Index Page<h1/>
{% endblock %}

Send_Emails/templates/main/signin.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<link href="{% static 'css/signin.css' %}" rel="stylesheet">
        <head lang="en">
                <meta charset="UTF-8" />
                <title></title>
        </head>
        <body>
		{% csrf_token %}
		<input type="text" id="login" name="login" placeholder="USERNAME">
	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript" src="{% static "js/signin.js" %}"></script>
</html>